// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AdvancedSoftwareDeveloperTrainingCampDbContext))]
    [Migration("20220907193415_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marka-18"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 2,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 200m,
                            Name = "Model-1"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 200m,
                            Name = "Model-2"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 700m,
                            Name = "Model-3"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 200m,
                            Name = "Model-4"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 200m,
                            Name = "Model-5"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 5,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 500m,
                            Name = "Model-6"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 500m,
                            Name = "Model-7"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 6,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 900m,
                            Name = "Model-8"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 7,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 200m,
                            Name = "Model-9"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 8,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-10"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 8,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-11"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-12"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-13"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 400m,
                            Name = "Model-14"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 400m,
                            Name = "Model-15"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 400m,
                            Name = "Model-16"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-17"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            CreatedDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DailyPrice = 300m,
                            Name = "Model-18"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Model", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
